package com.laks.tvseries.core.global

class GlobalConstants {
    companion object {
        const val SERVER_BASE_URL = "https://api.themoviedb.org/"
        const val SERVER_IMAGE_URL = "https://image.tmdb.org/t/p/w500/"
        const val SERVER_BACK_DROP_IMAGE_URL = "https://www.themoviedb.org/t/p/w1920_and_h800_multi_faces/"
        const val PACKAGE_NAME = "com.laks.tvseries"
        const val APP_PACKAGE_NAME = "com.laks.tvseries.pandora"
        const val MEDIA_DETAIL_ID = "media_detail_id"
        const val MEDIA_DETAIL_TYPE = "media_detail_type"
        const val ACTOR_DETAIL_ID = "actor_detail_id"
        const val KEY_ACTOR_MEDIA_LIST = "KEY_ACTOR_MEDIA_LIST"
        const val MOVIE_TYPE = "MOVIE_TYPE"
        const val ALL_MOVIE_TITLE = "ALL_MOVIE_TITLE"
        const val SHARED_LANGUAGE = "SHARED_LANGUAGE"
        const val SHARED_LANGUAGE_CODE = "SHARED_LANGUAGE_CODE"
        const val SHARED_LANGUAGE_COUNTRY = "SHARED_LANGUAGE_COUNTRY"
        const val SHARED_LANGUAGE_WITH_CODE_COUNTRY = "SHARED_LANGUAGE_WITH_CODE_COUNTRY"
        const val SHARED_NAME = "pandora_shared"
        const val FIREBASE_RANDOM_MOVIE_TABLE = "Random"
        const val FIREBASE_COLLECTION_SERIES_TABLE = "Collections"
        const val FIREBASE_MOD_LIS_MOVIE_TABLE = "ModList"
        const val FIREBASE_ABOUT_TABLE = "About"
        const val FIREBASE_TERM_OF_USE_TABLE = "TermOfUse"
        const val DEFAULT_EN_CODE = "en-US"
        const val DISCOVER_MEDIA_TITLE= "DISCOVER_MEDIA_TITLE"
        const val DISCOVER_MEDIA_TYPE= "DISCOVER_MEDIA_TYPE"
        const val YOUTUBE_VIDEO_ID = "YOUTUBE_VIDEO_ID"
        const val YOUTUBE_VIDEO_DURACTION = "YOUTUBE_VIDEO_DURACTION"
        const val IS_APP_KILL_NOTIFICATION = "IS_APP_KILL"
        const val SCREEN_TYPE = "SCREEN_TYPE"
        const val IS_APP_OPEN = "IS_APP_OPEN"
        const val GENRE_ID = "GENRE_ID"
        const val REWARD_ADS_RESULT_CODE = 12902
        const val IS_WATCH_ADS = "IS_WATCH_ADS"
        const val MOVIE_ADS_ID = "MOVIE_ADS_ID"
        const val RANDOM_MOVIE_SHOW_ADS = "RANDOM_MOVIE_SHOW_ADS"
        const val MOD_MOVIE_SHOW_ADS = "MOD_MOVIE_SHOW_ADS"
        const val COLLECTION_MODEL = "COLLECTION_MODEL"
    }
}